### ISSUE TITLE
any chance for a demo using jQuery-File-Upload basic plus UI ?

### ISSUE THREAD

**Issue by vesper8** [recca0120/upload#11]
it seems this package works with https://blueimp.github.io/jQuery-File-Upload/?

But you only show a demo using fileapi. Also it's a bit confusing your explanation of how to use this with Laravel 5. Any chance for a demo with multi-add, edit, delete functionality working laravel 5 and https://blueimp.github.io/jQuery-File-Upload/ basic plus UI ?

please that would be super useful!

**Comment by recca0120** [comment]
hi @vesper8 
I found a bug in jQuery-File-Upload,
I will release new version later...

**Comment by recca0120** [comment]
HI @vesper8 
demo here
https://github.com/recca0120/upload/blob/master/docs/demo/index.html
