### ISSUE TITLE
Integrate with dropzone.js

### ISSUE THREAD

**Issue by donguinesjay** [recca0120/upload#14]
Hi how can i Integrate this with dropzone js in laravel?

**Comment by recca0120** [comment]
https://github.com/recca0120/upload/blob/master/src/Plupload.php

like this

you need to implement two methods `receive` and `completedResponse`

**Comment by recca0120** [comment]
Hi
dropzone here

https://github.com/recca0120/upload/blob/master/docs/demo/index.html#L318-L333
