### ISSUE TITLE
fine uploader delete button not work~

### ISSUE THREAD

**Issue by ccyeh0901** [recca0120/upload#16]
Sir,
I've used the demo fine uploader to upload file successfully, but failed when deleting files pressing the trash button in the right below corner, below is the error message showed on console:

"fine-uploader.min.js:3 DELETE http://api.test/demo/server/endpoint.php/fc40d2c5-53d7-4d4d-a0ac-d648ef531b4f? 405 (Method Not Allowed)"

I'll appreciate that if you offer the endpoint.php file if possible to make the demo more useful to us, Thanks again.

![screen shot 2018-05-07 at 11 46 02 am](https://user-images.githubusercontent.com/16374458/39684132-4503030a-51ec-11e8-91d4-3bb3658cfcbe.jpg)

**Comment by recca0120** [comment]
You should implement delete method by yourself

**Comment by ccyeh0901** [comment]
i see, thank you～
