### ISSUE TITLE
Trouble with modifying storage paths

### ISSUE THREAD

**Issue by bethperk** [recca0120/upload#17]
I'm successfully uploading using FineUploader with chunking, but I'd like to modify the storage paths for where the files are stored, as I can't have the photos publicly available.  Can you tell me where to modify this data?  I tried changing it in the API.PHP file, but that wasn't it.  My files are being saved currently to a temp folder in the public/storage area.  I'd like to put them into a storage_path location called 'imageuploads'.  Thanks very much!

**Comment by recca0120** [comment]
in receive method you can do anything you want.

```php
use Illuminate\Http\JsonResponse;
use Recca0120\Upload\UploadManager;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class UploadController extends Controller
{
    public function upload(UploadManager $manager)
    {
        $driver = 'plupload'; // or 'fileapi'
        $inputName = 'file'; // $_FILES index;

        return $manager
            ->driver($driver)
            ->receive($inputName, function (UploadedFile $uploadedFile, $path, $domain, $api) {
                    // write something you want
            });
    }
}
```
